"""T038 Project Semantic Understanding Pack — validation tests.

Validates:
- Bundle completeness (9 files)
- Metadata consistency (project_id, canonical names, scores, is_selected)
- Semantic summary schema
- Stage extraction (>=2 stages for coarse)
- Core concept canonicalization (peak_idx not peak, smooth_detect not smooth)
- Test evidence extraction
- Real project quality gates
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

# Bundle paths generated by T038
BUNDLE_PATHS = [
    Path("/tmp/fpga_devmind/t038_coarse_semantic"),
    Path("/tmp/fpga_devmind/t038_fine_cfo_semantic"),
    Path("/tmp/fpga_devmind/t038_fft_semantic"),
]

# Quality gate thresholds
GATES = {
    "coarse": {"selected_precision_like": 0.70, "selected_recall_like": 0.875},
    "fine_cfo": {"selected_precision_like": 0.50, "selected_recall_like": 0.833},
    "fft": {"selected_precision_like": 0.583, "selected_recall_like": 0.833},
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


@pytest.fixture(params=BUNDLE_PATHS, ids=[p.name for p in BUNDLE_PATHS])
def bundle_dir(request: pytest.FixtureRequest) -> Path:
    return request.param


# ---------------------------------------------------------------------------
# Bundle completeness
# ---------------------------------------------------------------------------


def test_bundle_has_9_files(bundle_dir: Path) -> None:
    """Each T038 bundle must contain exactly 9 files."""
    expected = {
        "concept_candidates.json",
        "discovery_eval_report.md",
        "discovery_eval_result.json",
        "project_semantic_summary.json",
        "project_understanding_graph.json",
        "project_understanding_index.json",
        "project_understanding.md",
        "project_understanding.mmd",
        "run_metadata.json",
    }
    files = {p.name for p in bundle_dir.iterdir() if p.is_file()}
    assert files == expected, f"Missing or extra files: {expected ^ files}"


# ---------------------------------------------------------------------------
# Metadata consistency
# ---------------------------------------------------------------------------


def test_metadata_project_id(bundle_dir: Path) -> None:
    metadata = _load_json(bundle_dir / "run_metadata.json")
    assert metadata.get("project_id"), "project_id must be non-empty"
    assert metadata["project_id"] != "project", "project_id should be real project name"


def test_metadata_selected_canonical_concepts(bundle_dir: Path) -> None:
    metadata = _load_json(bundle_dir / "run_metadata.json")
    selected = metadata.get("selected_canonical_concepts", [])
    assert isinstance(selected, list), "selected_canonical_concepts must be a list"
    assert len(selected) > 0, "selected_canonical_concepts must not be empty"


def test_metadata_selected_concept_count(bundle_dir: Path) -> None:
    metadata = _load_json(bundle_dir / "run_metadata.json")
    count = metadata.get("selected_concept_count")
    selected = metadata.get("selected_canonical_concepts", [])
    assert count == len(selected), "selected_concept_count must match list length"


def test_metadata_eval_metrics(bundle_dir: Path) -> None:
    metadata = _load_json(bundle_dir / "run_metadata.json")
    eval_metrics = metadata.get("eval_metrics", {})
    assert "selected_precision_like" in eval_metrics, "eval_metrics must have selected_precision_like"
    assert "selected_recall_like" in eval_metrics, "eval_metrics must have selected_recall_like"


# ---------------------------------------------------------------------------
# Concept candidates fields
# ---------------------------------------------------------------------------


def test_candidates_have_t038_fields(bundle_dir: Path) -> None:
    candidates = _load_json(bundle_dir / "concept_candidates.json")
    assert isinstance(candidates, list), "candidates must be a list"
    assert len(candidates) > 0, "candidates must not be empty"

    for c in candidates:
        assert "canonical_name" in c, "candidate must have canonical_name"
        assert "score" in c, "candidate must have score"
        assert isinstance(c["score"], int), "score must be int"
        assert "is_selected" in c, "candidate must have is_selected"
        assert isinstance(c["is_selected"], bool), "is_selected must be bool"
        assert "rejection_reason" in c, "candidate must have rejection_reason"
        assert "evidence_counts_by_stage" in c, "candidate must have evidence_counts_by_stage"
        assert isinstance(c["evidence_counts_by_stage"], dict), "evidence_counts_by_stage must be dict"


# ---------------------------------------------------------------------------
# Semantic summary schema
# ---------------------------------------------------------------------------


def test_semantic_summary_schema(bundle_dir: Path) -> None:
    ss = _load_json(bundle_dir / "project_semantic_summary.json")
    required_top = [
        "schema_version", "project_id", "project_root", "project_kind_hint",
        "top_level_purpose", "pipeline_stages", "core_concepts",
        "implementation_modules", "dataflow_summary", "evidence_quality_summary",
        "uncertainty_summary", "test_coverage_summary", "source_provenance",
    ]
    for field in required_top:
        assert field in ss, f"semantic_summary missing top-level field: {field}"

    assert ss["schema_version"] == "project-semantic-summary-0.1"
    assert isinstance(ss["pipeline_stages"], list)
    assert isinstance(ss["core_concepts"], list)
    assert isinstance(ss["implementation_modules"], list)

    # Evidence quality summary
    ev = ss["evidence_quality_summary"]
    for field in ["strong_direct", "medium_structural", "weak_name_only", "inferred"]:
        assert field in ev, f"evidence_quality_summary missing {field}"
        assert isinstance(ev[field], int)

    # Uncertainty summary
    unc = ss["uncertainty_summary"]
    for field in ["inferred_claims", "weak_only_links", "naming_only_links",
                  "missing_l5_l6", "missing_rtl", "missing_test_evidence"]:
        assert field in unc, f"uncertainty_summary missing {field}"

    # Test coverage summary
    tc = ss["test_coverage_summary"]
    for field in ["test_files_present", "total_test_files",
                  "concepts_with_test_match", "concepts_without_test_match", "per_concept"]:
        assert field in tc, f"test_coverage_summary missing {field}"

    # Source provenance
    prov = ss["source_provenance"]
    assert "summary_generated_from" in prov
    assert "generation_timestamp" in prov
    assert "generator" in prov


# ---------------------------------------------------------------------------
# Stage extraction
# ---------------------------------------------------------------------------


def test_pipeline_stages_exist(bundle_dir: Path) -> None:
    ss = _load_json(bundle_dir / "project_semantic_summary.json")
    assert len(ss["pipeline_stages"]) >= 1, "must have at least 1 pipeline stage"


# ---------------------------------------------------------------------------
# Core concept canonicalization
# ---------------------------------------------------------------------------


def test_core_concepts_canonicalized(bundle_dir: Path) -> None:
    ss = _load_json(bundle_dir / "project_semantic_summary.json")
    canonical_names = [c["canonical_name"] for c in ss["core_concepts"]]

    # peak → peak_idx (not raw "peak")
    if any("peak" in n for n in canonical_names):
        assert "peak_idx" in canonical_names, "peak should be canonicalized to peak_idx"
        assert "peak" not in canonical_names, "raw 'peak' should not appear as canonical"

    # smooth → smooth_detect
    if any("smooth" in n for n in canonical_names):
        assert "smooth_detect" in canonical_names, "smooth should be canonicalized to smooth_detect"

    # No duplicates
    assert len(canonical_names) == len(set(canonical_names)), "canonical names must be unique"


# ---------------------------------------------------------------------------
# Real project gates
# ---------------------------------------------------------------------------


def test_coarse_top_level_purpose() -> None:
    """coarse_sync bundle must mention OFDM coarse sync in purpose."""
    path = Path("/tmp/fpga_devmind/t038_coarse_semantic")
    if not path.exists():
        pytest.skip("coarse bundle not found")
    ss = _load_json(path / "project_semantic_summary.json")
    purpose = ss["top_level_purpose"].lower()
    assert "ofdm" in purpose, "top_level_purpose must mention OFDM"
    assert "coarse" in purpose, "top_level_purpose must mention coarse"


@pytest.mark.parametrize("project,expected_prec,expected_rec", [
    ("coarse", 0.70, 0.875),
    ("fine_cfo", 0.50, 0.833),
    ("fft", 0.583, 0.833),
])
def test_quality_gate(project: str, expected_prec: float, expected_rec: float) -> None:
    """Quality gates from T036/T037 must still pass after T038 changes."""
    path = Path(f"/tmp/fpga_devmind/t038_{project}_semantic")
    if not path.exists():
        pytest.skip(f"{project} bundle not found")

    eval_result = _load_json(path / "discovery_eval_result.json")
    prec = eval_result.get("selected_precision_like", 0.0)
    rec = eval_result.get("selected_recall_like", 0.0)

    assert prec >= expected_prec - 0.001, (
        f"{project} precision {prec} < {expected_prec}"
    )
    assert rec >= expected_rec - 0.001, (
        f"{project} recall {rec} < {expected_rec}"
    )
